FROM alpine:3.8

RUN apk add --update nodejs nodejs-npm

WORKDIR /app

COPY . ./

ARG CIRCLE_SHA1
ARG CIRCLE_BUILD_URL
ARG CIRCLE_USERNAME
ARG CIRCLE_PROJECT_REPONAME
ARG CIRCLE_BUILD_NUM
ARG CIRCLE_WORKFLOW_ID
ARG CI_PULL_REQUEST

ENV CIRCLE_SHA1=$CIRCLE_SHA1
ENV CIRCLE_BUILD_URL=$CIRCLE_BUILD_URL
ENV CIRCLE_USERNAME=$CIRCLE_USERNAME
ENV CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME
ENV CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM
ENV CIRCLE_WORKFLOW_ID=$CIRCLE_WORKFLOW_ID
ENV CI_PULL_REQUEST=$CI_PULL_REQUEST

# Not supported in Heroku
# EXPOSE 3000

CMD node app.js