#!/bin/bash

heroku container:push web \
       --arg CIRCLE_BUILD_URL=$CIRCLE_BUILD_URL,CIRCLE_SHA1=$CIRCLE_SHA1,CIRCLE_USERNAME=$CIRCLE_USERNAME,CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME,CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM,CIRCLE_WORKFLOW_ID=$CIRCLE_WORKFLOW_ID,CI_PULL_REQUEST=$CI_PULL_REQUEST \
	   --app damp-bastion-21277

heroku container:release web --app damp-bastion-21277
